import { RESOURCES, STATUS_OPTIONS } from "@/utils/constants";

export const resourceConfigs = {
  [RESOURCES.HERO_BANNERS]: {
    resource: RESOURCES.HERO_BANNERS,
    title: "Hero Banners",
    description: "Large homepage hero slides with CTAs.",
    basePath: "/home/hero-banners",
    imageKey: "image_url",
    large: true,
    folder: "hero-banners",
    fields: [
      { name: "image_url", label: "Banner image", type: "image", required: true, full: true, aspect: "video" },
      { name: "title", label: "Title", required: true },
      { name: "title_accent", label: "Title accent" },
      { name: "subtitle", label: "Subtitle" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "primary_btn_text", label: "Primary button text" },
      { name: "primary_btn_link", label: "Primary button link" },
      { name: "secondary_btn_text", label: "Secondary button text" },
      { name: "secondary_btn_link", label: "Secondary button link" },
      { name: "display_order", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
  },
  [RESOURCES.HOME_PROJECTS]: {
    resource: RESOURCES.HOME_PROJECTS,
    title: "Latest Projects",
    description: "Homepage project highlights.",
    basePath: "/home/projects",
    folder: "home-projects",
    fields: [
      { name: "image_url", label: "Project image", type: "image", required: true, full: true },
      { name: "title", label: "Title", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "button_text", label: "Button text" },
      { name: "button_link", label: "Button link" },
      { name: "display_order", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
  },
  [RESOURCES.HOME_EVENTS]: {
    resource: RESOURCES.HOME_EVENTS,
    title: "Home Upcoming Events",
    description: "Event teasers shown on the homepage.",
    basePath: "/home/events",
    folder: "home-events",
    fields: [
      { name: "image_url", label: "Event image", type: "image", required: true, full: true },
      { name: "title", label: "Title", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "venue", label: "Venue" },
      { name: "event_date", label: "Event date" },
      { name: "event_time", label: "Event time" },
      { name: "speaker", label: "Speaker" },
      { name: "registration_link", label: "Registration link" },
      { name: "button_text", label: "Button text" },
      { name: "display_order", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
  },
  [RESOURCES.TESTIMONIALS]: {
    resource: RESOURCES.TESTIMONIALS,
    title: "Testimonials",
    description: "Homepage testimonials and quotes.",
    basePath: "/home/testimonials",
    imageKey: "profile_image",
    titleKey: "name",
    folder: "testimonials",
    fields: [
      { name: "profile_image", label: "Profile image", type: "image", aspect: "square" },
      { name: "name", label: "Name", required: true },
      { name: "designation", label: "Designation" },
      { name: "organisation", label: "Organisation" },
      { name: "location", label: "Location" },
      { name: "message", label: "Message", type: "textarea", required: true },
      { name: "display_order", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
  },
  [RESOURCES.FEATURED_EVENTS]: {
    resource: RESOURCES.FEATURED_EVENTS,
    title: "Featured Events",
    description: "Highlighted events on the Events page.",
    basePath: "/events/featured",
    imageKey: "banner_image",
    large: true,
    folder: "featured-events",
    fields: [
      { name: "banner_image", label: "Banner image", type: "image", required: true, full: true },
      { name: "title", label: "Title", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "venue", label: "Venue" },
      { name: "event_date", label: "Event date" },
      { name: "event_time", label: "Event time" },
      { name: "category", label: "Category" },
      { name: "registration_link", label: "Registration link" },
      { name: "display_order", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
  },
  [RESOURCES.UPCOMING_EVENTS]: {
    resource: RESOURCES.UPCOMING_EVENTS,
    title: "Upcoming Events",
    description: "Upcoming events grid on the Events page.",
    basePath: "/events/upcoming",
    folder: "upcoming-events",
    fields: [
      { name: "image_url", label: "Event image", type: "image", required: true, full: true },
      { name: "title", label: "Title", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "venue", label: "Venue" },
      { name: "event_date", label: "Event date" },
      { name: "event_time", label: "Event time" },
      { name: "category", label: "Category" },
      { name: "registration_link", label: "Registration link" },
      { name: "display_order", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
  },
  [RESOURCES.GALLERY_ITEMS]: {
    resource: RESOURCES.GALLERY_ITEMS,
    title: "Past Gallery",
    description: "Photo gallery items from past events.",
    basePath: "/events/gallery",
    folder: "gallery-items",
    fields: [
      { name: "image_url", label: "Gallery image", type: "image", required: true, full: true },
      { name: "title", label: "Title", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "category", label: "Category" },
      { name: "year", label: "Year" },
      { name: "location", label: "Location" },
      { name: "alt_text", label: "Alt text" },
      { name: "display_order", label: "Display order", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
  },
};

export function crumbsFor(config, extra = []) {
  return [
    { label: "Dashboard", href: "/dashboard" },
    { label: config.title, href: config.basePath },
    ...extra,
  ];
}
